#!/usr/bin/env python3
"""Minimal web app for running and viewing Agent-Alpha outputs locally."""

from __future__ import annotations

import json
import os
import shlex
import subprocess
import threading
import time
import uuid
from http import HTTPStatus
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse


ROOT = Path(__file__).resolve().parents[1]
APP_DIR = ROOT / "app"
SRC_DIR = APP_DIR / "src"
OUTPUTS_DIR = ROOT / "outputs"
SETTINGS_PATH = APP_DIR / "settings.json"
ENV_ENTERPRISE_PATH = ROOT / ".env.enterprise"

DEFAULT_SETTINGS: dict[str, Any] = {
    "defaults": {
        "provider": "openai",
        "deep_model": "gpt-5.4",
        "quick_model": "gpt-5.4-mini",
        "debate_rounds": 1,
        "checkpoint": False,
    },
    "api_keys": {
        "OPENAI_API_KEY": "",
        "ANTHROPIC_API_KEY": "",
        "GOOGLE_API_KEY": "",
        "AZURE_OPENAI_API_KEY": "",
    },
    "ui": {"auto_refresh_seconds": 2},
}

PROVIDERS = [
    "openai",
    "google",
    "anthropic",
    "azure",
    "xai",
    "deepseek",
    "qwen",
    "glm",
    "ollama",
    "openrouter",
]

PROVIDER_MODELS: dict[str, list[str]] = {
    "openai": ["gpt-5.4", "gpt-5.4-mini", "gpt-4.1", "gpt-4o"],
    "google": ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"],
    "anthropic": ["claude-opus-4-1", "claude-sonnet-4", "claude-3-7-sonnet"],
    "azure": ["gpt-4.1", "gpt-4o", "gpt-5.4"],
    "xai": ["grok-3", "grok-2-latest"],
    "deepseek": ["deepseek-chat", "deepseek-reasoner"],
    "qwen": ["qwen-max", "qwen-plus"],
    "glm": ["glm-4", "glm-4-plus"],
    "ollama": ["llama3.1", "qwen2.5", "mistral"],
    "openrouter": ["openai/gpt-4o", "anthropic/claude-3.7-sonnet", "google/gemini-2.5-pro"],
}

jobs_lock = threading.Lock()
jobs: dict[str, dict[str, Any]] = {}


def _ensure_settings() -> None:
    APP_DIR.mkdir(parents=True, exist_ok=True)
    if not SETTINGS_PATH.exists():
        SETTINGS_PATH.write_text(json.dumps(DEFAULT_SETTINGS, indent=2), encoding="utf-8")


def _read_settings() -> dict[str, Any]:
    _ensure_settings()
    try:
        loaded = json.loads(SETTINGS_PATH.read_text(encoding="utf-8"))
        defaults = loaded.get("defaults", {})
        api_keys = loaded.get("api_keys", {})
        ui = loaded.get("ui", {})
        merged = {
            "defaults": {**DEFAULT_SETTINGS["defaults"], **defaults},
            "api_keys": {**DEFAULT_SETTINGS["api_keys"], **api_keys},
            "ui": {**DEFAULT_SETTINGS["ui"], **ui},
        }
        return merged
    except Exception:
        return DEFAULT_SETTINGS.copy()


def _write_settings(payload: dict[str, Any]) -> dict[str, Any]:
    current = _read_settings()
    merged = {
        "defaults": {**current["defaults"], **payload.get("defaults", {})},
        "api_keys": {**current["api_keys"], **payload.get("api_keys", {})},
        "ui": {**current["ui"], **payload.get("ui", {})},
    }
    SETTINGS_PATH.write_text(json.dumps(merged, indent=2), encoding="utf-8")
    _sync_env_enterprise(merged["api_keys"])
    return merged


def _sync_env_enterprise(api_keys: dict[str, str]) -> None:
    lines = [
        "# Auto-generated by app/server.py settings sync",
        "# Local development secrets for Agent-Alpha web app",
    ]
    for key, value in api_keys.items():
        if value:
            safe_value = value.replace("\n", "").strip()
            lines.append(f"{key}={safe_value}")
    ENV_ENTERPRISE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _json_response(handler: SimpleHTTPRequestHandler, payload: dict[str, Any], status: int = 200) -> None:
    data = json.dumps(payload).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(data)))
    handler.send_header("Cache-Control", "no-store")
    handler.end_headers()
    handler.wfile.write(data)


def _read_json_body(handler: SimpleHTTPRequestHandler) -> dict[str, Any]:
    raw_len = int(handler.headers.get("Content-Length", "0"))
    raw = handler.rfile.read(raw_len) if raw_len > 0 else b"{}"
    try:
        decoded = json.loads(raw.decode("utf-8"))
        return decoded if isinstance(decoded, dict) else {}
    except Exception:
        return {}


def _normalize_tickers(raw_tickers: str) -> list[str]:
    tickers: list[str] = []
    seen: set[str] = set()
    for part in raw_tickers.split(","):
        ticker = part.strip().upper()
        if ticker and ticker not in seen:
            seen.add(ticker)
            tickers.append(ticker)
    return tickers


def _start_job(payload: dict[str, Any]) -> dict[str, Any]:
    settings = _read_settings()
    defaults = settings["defaults"]

    tickers_input = str(payload.get("tickers", "")).strip()
    tickers = _normalize_tickers(tickers_input)
    if not tickers:
        raise ValueError("Provide at least one ticker symbol.")

    provider = str(payload.get("provider") or defaults["provider"]).strip()
    deep_model = str(payload.get("deep_model") or defaults["deep_model"]).strip()
    quick_model = str(payload.get("quick_model") or defaults["quick_model"]).strip()
    analysis_date = str(payload.get("date", "")).strip()
    debate_rounds = int(payload.get("debate_rounds", defaults["debate_rounds"]))
    checkpoint = bool(payload.get("checkpoint", defaults["checkpoint"]))

    cmd: list[str] = [
        "python",
        "scripts/run_today.py",
        "--tickers",
        ",".join(tickers),
        "--provider",
        provider,
        "--deep-model",
        deep_model,
        "--quick-model",
        quick_model,
        "--debate-rounds",
        str(debate_rounds),
    ]
    if analysis_date:
        cmd.extend(["--date", analysis_date])
    if checkpoint:
        cmd.append("--checkpoint")

    job_id = f"run_{uuid.uuid4().hex[:10]}"
    job = {
        "id": job_id,
        "status": "queued",
        "created_at": int(time.time()),
        "updated_at": int(time.time()),
        "command": " ".join(shlex.quote(part) for part in cmd),
        "args": {
            "tickers": tickers,
            "provider": provider,
            "deep_model": deep_model,
            "quick_model": quick_model,
            "debate_rounds": debate_rounds,
            "date": analysis_date,
            "checkpoint": checkpoint,
        },
        "logs": [],
        "exit_code": None,
    }

    with jobs_lock:
        jobs[job_id] = job

    threading.Thread(target=_run_subprocess_job, args=(job_id, cmd), daemon=True).start()
    return job


def _append_log(job: dict[str, Any], line: str) -> None:
    clean = line.rstrip("\n")
    if not clean:
        return
    logs: list[str] = job["logs"]
    logs.append(clean)
    if len(logs) > 500:
        del logs[: len(logs) - 500]


def _run_subprocess_job(job_id: str, cmd: list[str]) -> None:
    with jobs_lock:
        job = jobs[job_id]
        job["status"] = "running"
        job["updated_at"] = int(time.time())

    proc = subprocess.Popen(
        cmd,
        cwd=str(ROOT),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        env=os.environ.copy(),
    )

    assert proc.stdout is not None
    for line in proc.stdout:
        with jobs_lock:
            job = jobs.get(job_id)
            if not job:
                break
            _append_log(job, line)
            job["updated_at"] = int(time.time())

    exit_code = proc.wait()
    with jobs_lock:
        job = jobs.get(job_id)
        if job:
            job["exit_code"] = exit_code
            job["status"] = "completed" if exit_code == 0 else "failed"
            job["updated_at"] = int(time.time())


def _read_metadata(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _list_reports() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if not OUTPUTS_DIR.exists():
        return rows

    for date_dir in sorted([p for p in OUTPUTS_DIR.iterdir() if p.is_dir()], reverse=True):
        if date_dir.name.startswith("_"):
            continue
        for ticker_dir in sorted([p for p in date_dir.iterdir() if p.is_dir()]):
            report_path = ticker_dir / "report.md"
            metadata_path = ticker_dir / "metadata.json"
            if not report_path.exists():
                continue
            metadata = _read_metadata(metadata_path) if metadata_path.exists() else {}
            rows.append(
                {
                    "date": date_dir.name,
                    "ticker": ticker_dir.name,
                    "final_rating": metadata.get("final_rating", "Unknown"),
                    "overall_confidence": metadata.get("overall_confidence", None),
                    "has_metadata": metadata_path.exists(),
                }
            )
    return rows


def _get_report(date: str, ticker: str) -> dict[str, Any]:
    base = OUTPUTS_DIR / date / ticker
    report_path = base / "report.md"
    metadata_path = base / "metadata.json"
    if not report_path.exists():
        raise FileNotFoundError("Report not found for that date/ticker.")

    report_text = report_path.read_text(encoding="utf-8")
    metadata = _read_metadata(metadata_path) if metadata_path.exists() else {}
    return {"date": date, "ticker": ticker, "report": report_text, "metadata": metadata}


class AppHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, directory=str(SRC_DIR), **kwargs)

    def do_GET(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/api/health":
            _json_response(self, {"ok": True, "service": "agent-alpha-minimal-web"})
            return

        if path == "/api/providers":
            _json_response(self, {"providers": PROVIDERS})
            return

        if path == "/api/models":
            _json_response(self, {"models_by_provider": PROVIDER_MODELS})
            return

        if path == "/api/settings":
            _json_response(self, {"settings": _read_settings()})
            return

        if path == "/api/runs":
            with jobs_lock:
                rows = sorted(jobs.values(), key=lambda item: item["created_at"], reverse=True)
            _json_response(self, {"runs": rows[:25]})
            return

        if path.startswith("/api/runs/"):
            job_id = path.split("/")[-1]
            with jobs_lock:
                job = jobs.get(job_id)
            if not job:
                _json_response(self, {"error": "Run not found."}, status=404)
                return
            _json_response(self, {"run": job})
            return

        if path == "/api/reports":
            _json_response(self, {"reports": _list_reports()})
            return

        if path == "/api/report":
            q = parse_qs(parsed.query)
            date = (q.get("date") or [""])[0]
            ticker = (q.get("ticker") or [""])[0]
            if not date or not ticker:
                _json_response(self, {"error": "Provide date and ticker query params."}, status=400)
                return
            try:
                payload = _get_report(date, ticker)
                _json_response(self, payload)
            except FileNotFoundError as exc:
                _json_response(self, {"error": str(exc)}, status=404)
            return

        if path == "/":
            self.path = "/index.html"
        return super().do_GET()

    def do_POST(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)
        path = parsed.path
        payload = _read_json_body(self)

        if path == "/api/run":
            try:
                job = _start_job(payload)
                _json_response(self, {"run": job}, status=HTTPStatus.ACCEPTED)
            except Exception as exc:
                _json_response(self, {"error": str(exc)}, status=400)
            return

        if path == "/api/settings":
            settings = _write_settings(payload)
            _json_response(self, {"settings": settings})
            return

        _json_response(self, {"error": "Not found"}, status=404)

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A003
        # Keep server console output minimal and app-focused.
        return


def main() -> int:
    _ensure_settings()
    host = "127.0.0.1"
    port = int(os.environ.get("APP_PORT", "8787"))
    server = ThreadingHTTPServer((host, port), AppHandler)
    print(f"Agent-Alpha app running at http://{host}:{port}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
